### ISSUE TITLE
Add security configuration 

### ISSUE THREAD

**Issue by olehsov** [Farm-Trade/farm-trade-backend#20]
Add base security configuration
- [ ] User password should be encoded
- [ ] Role enum should  be implemented with GrantedAuthority
- [ ] User should be implemented with UserDetails
- [ ] UserService should be implemented with UserDetailService
- [ ] Add basic auth as authenticated method

**Comment by Korbut-Dima** [comment]
UserService should be implemented with UserDetailService or you mean extended

**Comment by olehsov** [comment]
@Korbut-Dima extended
